### ISSUE TITLE
Traceback is disabled via bootloader option.

### ISSUE THREAD

**Issue by TheLocalMoon** [BarsTiger/KotoPad#1]
the fuck is this

**Comment by BarsTiger** [comment]
I cannot reproduce issue with this information. Provide full traceback message, system info and your actions

**Comment by BarsTiger** [comment]
Seems to be an issue with antivirus. Try adding app folder to exclusions or turning antivirus off. 
Also, check your system. Build works only for newest windows 10/11.
Another solution - install Python, download sources and build them by yourself or launch with python.

**Comment by TheLocalMoon** [comment]
did not help
